name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  trabalhoConclusao:    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Executando Testes Trabalho de Conclusão
        run: npx mocha ./TrabalhoConclusao/trabalho-final.js
